### ISSUE TITLE
request for Hackage release of `indexed-traversable-instances` with `tasty` 1.5

### ISSUE THREAD

**Issue by peterbecich** [haskellari/indexed-traversable#36]
The latest release on Hackage is earlier than this change.

https://github.com/haskellari/indexed-traversable/blame/96a2a4bd8be86bcd0f2803dd0170236f57ca8b28/indexed-traversable-instances/indexed-traversable-instances.cabal#L90

https://hackage.haskell.org/package/indexed-traversable-instances

Can a revision be published? It will help to build the library on `nixpkgs` in the future.

Thank you

**Comment by phadej** [comment]
Done
